sudo: required
services:
 - docker
deploy:
 provider: elasticbeanstalk
 region: "ap-south-1"
 app: "docker-react"
 env: "docker-env"
 bucket_name: "elasticbeanstalk-ap-south-1-493432698281"
 bucket_path: "docker-react"
 on:
  branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key:
 secure: "$AWS_SECRET_KEY"